[project]
name = "flask-github-actions-demo"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "black>=25.1.0",
    "mypy>=1.15.0",
    "pip>=25.1.1",
    "sqlalchemy",
]
